### ISSUE TITLE
Consider publishing to npm

### ISSUE THREAD

**Issue by grrowl** [bobvanderlinden/probot-auto-merge#113]
We're running a number of probots internally, so we expose one endpoint as one "app" and call multiple plugins within that. Would you consider publishing `probot-auto-merge` on npm so we can more simply depend on that rather than the github repository?

**Comment by bobvanderlinden** [comment]
I currently do not manage versions: what's on master is automatically deployed to Heroku.

Do you know of a good way to add this to the current workflow?

**Comment by grrowl** [comment]
Other probot projects use https://github.com/getsentry/probot-release, but this requires running `npm pack` and committing the resulting `package.tgz`. Otherwise we use https://github.com/semantic-release/semantic-release but it needs a bit more setting up (you'll want to add the `@semantic-release/git` plugin configured to commit and push back the updated `package.json` files to git).

Honestly the first option is easiest. Currently you can't depend directly on the github repo because the library must be built into require-able JS from TS.

**Comment by bobvanderlinden** [comment]
I initially looked at probot-release, but there were quite a few downsides:

* Requires me to setup another probot instance
* Commit package.tgz
* It seems unmaintained for some time now

I went for semantic-release. Setup didn't look too bad, but I still have to see how well it works.

`@semantic-release/git` doesn't sound like something I'd like to do. Because every merge of a PR will probably result in a new release, it has to commit the new version every time a merge has happened. But maybe I'm misunderstanding how to use it?

**Comment by grrowl** [comment]
i believe because the `git` plugin commits as `chore:`, it doesn't trigger a new version. If the `semantic-release` bot triggers and doesn't find  `fix:` or `feat:` commits, it won't trigger a release (i believe). 

that said — it's working and it publishes to the github releases page so i'm more than satisfied with its current state :D thank you so much !

**Comment by bobvanderlinden** [comment]
We'll see how well it works. Probably needs more tweaking to trigger the releases. Worst that could happen is the npm package being outdated.
