### ISSUE TITLE
Update Branch doesn't work properly

### ISSUE THREAD

**Issue by dkhmelenko** [bobvanderlinden/probot-auto-merge#76]
When configuration set up to `true` for update branch, after the PR is get approved and Update Branch action needed, nothing will happen.

**Comment by dkhmelenko** [comment]
Sorry, I didn't get what you mean. What does it mean that `updating the branch did not succeed`? Will user see anyway that the branch is updated?

**Comment by bobvanderlinden** [comment]
Can you add the following to your `auto-merge.yaml`:

```
reportStatus: true
```

That will make the not report on its status and should also report on errors that happen when merging and updating a branch.

After setting the confirmation option you can retrigger a PR by adding/removing a label for instance.

**Comment by bobvanderlinden** [comment]
It was an experimental feature, but you're right. It's now working quite stable, so I've added it to the readme. Thanks for the reminder.

Did the status reporting help you determine the cause of not automatically updating branches?

**Comment by dkhmelenko** [comment]
I actually didn't try it yet, since as you already mentioned: "It's now working quite stable". 

I think, for me now the biggest pain point is to have prioritization described in https://github.com/bobvanderlinden/probot-auto-merge/issues/92 :)

Let me know there what you think, maybe I can prepare PR for that.

Regarding this issue - it's solved, no more action required. Thank you!

**Comment by bobvanderlinden** [comment]
I think I ran into the exact same issue as you did. With one of my PRs (#94).

It showed that auto-merge tried to merge instead of update, because it didn't think it was needed to update: the commit of the HEAD of base branch was equal to the commit of the base of the PR branch. That is strange, because GitHub actuall thought it was still needed to update the branch somehow. I have seen this happen before and I'm beginning to suspect that GitHub isn't supplying the right information or that GitHub has some other algorithm to determine whether a branch should be updated.

That said, I want to move towards using more of the preview APIs (as mentioned #92) and one of those APIs is querying the mergeable state of a PR. That makes it much easier to determine whether to update a branch, wait for blocking checks or just merge, as auto-merge can reuse GitHub's algorithms to determine in which state the PR is.

That should resolve this issue. It's a hard one to reproduce, so I think it's best to keep this one open for the time being.
