### ISSUE TITLE
When clicking on a new app - new app is without permissions

### ISSUE THREAD

**Issue by guy-lud** [bobvanderlinden/probot-auto-merge#78]
Hi,

We've just came a cross this project and it seems a great solution for our need.
We did as the README suggested and when clicking on register new app the manifest is empty.

Should it be like so ?

**Comment by bobvanderlinden** [comment]
I'm not sure I understand what you mean by manifest? Can you send a screenshot so I know what you mean?

**Comment by guy-lud** [comment]
What i am trying to understand is do we have to use probot-auto-merge github app or can we use our own app?  
It's a bit of an issue to let the app access to our code base

**Comment by bobvanderlinden** [comment]
If it's an issue to let my instance of auto-merge have rights to repos, then by all means use a self-hosted instance. The self-hosted instance does need to be set up properly though. You need to configure which rights the app needs. Those rights will be requested upon installation.

From your screenshot it seems the app does not have many rights configured, so that's something that you need to look at. I have not documented which rights I am using. I'm currently on mobile, so can't properly check this. Since the instance and installation are both your own, you can start with adding all permissions and events to the app.

**Comment by guy-lud** [comment]
thank you.
Sounds logical
